### ISSUE TITLE
Library Management System

### ISSUE THREAD

**Issue by PulkitMishra** [IIITKalyaniFOSC/todo#2]
Seen how the records for our library are kept?    Yes!
Is that how it should happen?   No!

Why not develop a software to handle basic housekeeping functions of a library?

**Comment by abhishekti7** [comment]
@PulkitMishra I know for sure that the second year guys are developing this.

**Comment by PulkitMishra** [comment]
@zeus0789 will close the issue if they are *after* they upload the source code on GitHub. If not this could be a good project to work on. Something, that our college can actually use.
Views @anubhavp28

**Comment by anubhavp28** [comment]
I have a library management system. I made it for my school in 8th grade. I can give it to our college. Written in PHP, HTML, JS & CSS

**Comment by anubhavp28** [comment]
@PulkitMishra Personally I hate working on these kinds of simple database applications, the work mostly seems monotonous and gives no learning curve.

**Comment by PulkitMishra** [comment]
@anubhavp28 agree on that. My intention was more on building something that can actually be used by the college. Anyway, closing this issue then.
